### ISSUE TITLE
Line without IN seems not recognized

### ISSUE THREAD

**Issue by x70b1** [cmur2/language-zonefile#1]
Hi, great work!

It seems that lines without the record class `IN` dont get recognized. There is a rule according to which the class only has to be written in the first record. In addition, there are apparently servers that don't need any class at all.

Is there already a fix for this?

**Comment by cmur2** [comment]
Hi, I didn't bother to support all possible variations that are allowed per https://www.ietf.org/rfc/rfc1035.txt but if you're using that notation without `IN` class I can surely try to support this?

**Comment by x70b1** [comment]
That would be nice!

**Comment by cmur2** [comment]
Should be fixed in https://github.com/cmur2/language-zonefile/commit/1f64694e75eaf791f1bfac314b5f09ce1dc4173c and is published as 1.1.1 release.

**Comment by x70b1** [comment]
It works. Awesome!
