### ISSUE TITLE
wrong color for content with more than 95 letters

### ISSUE THREAD

**Issue by x70b1** [cmur2/language-zonefile#2]
Hi

If I wrote a record content with more than 95 letters the text color changes to grey instead of green.
is this defined somewhere and wanted or is this a bug?

**Comment by cmur2** [comment]
It could be a bug but before investigating please have a look whether you are affected by https://github.com/atom/language-json/issues/1 and https://github.com/atom/atom/issues/1667 (which I solve for me using https://atom.io/packages/grammar-token-limit).

**Comment by x70b1** [comment]
Oh, looks good! `grammar-token-limit` solves it.
